# Generated by Django 5.2.16 on 2026-07-21 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_watts', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('cooling', 'Cooling'), ('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('electronics', 'Electronics'), ('lighting', 'Lighting'), ('water', 'Water'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon slug used by the frontend', max_length=40)),
                ('has_inverter_alternative', models.BooleanField(default=False)),
                ('inverter_savings_pct', models.PositiveSmallIntegerField(default=0, help_text='Approx. % savings if switched to an inverter/energy-efficient model')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TariffBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('A', 'Band A'), ('B', 'Band B'), ('C', 'Band C'), ('D', 'Band D'), ('E', 'Band E')], max_length=1)),
                ('rate_per_kwh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_hours_supply', models.PositiveSmallIntegerField(help_text='NERC-guaranteed minimum average hours of daily supply for this band')),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_bands', to='calculator.disco')),
            ],
            options={
                'ordering': ['disco', 'band'],
                'unique_together': {('disco', 'band')},
            },
        ),
    ]
