# Generated by Django 5.2.16 on 2026-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_waitlistsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='coverage',
            field=models.CharField(blank=True, help_text="States/areas this Disco serves, e.g. 'FCT, Niger, Kogi, Nasarawa'", max_length=200),
        ),
    ]
